lab 3 version 1
PdxCodeGuild/class_wallaby pull request #18
Opened 2021-07-01 22:56 UTC by PBHIPTOP

2021-07-02 03:21 UTC, PBHIPTOP reviewed
I believe this is the updated lab 3 v2.  A few tweaks were made.

2021-07-03 03:25 UTC, pjz987 requested changes
Hey Patrick. do `git pull` on this branch to get a `feedback/` directory in your code folder.  I modified lab3v1 and v2 to catch errors and bugs.  Run the two files inside of `class_wallaby/code/patrick/feedback/` to see the results.  Let me know if you have any questions.

2021-07-08 01:38 UTC, pjz987 approved these changes

2021-07-08 01:38 UTC, pjz987 commented on code/patrick/lab3v1.py
> +    if len(str(given_number)) == 1 and given_number == 0:
good stuff!

2021-07-08 01:38 UTC, merged